"""Typer CLI entry. Wires config → embedder → runner → reporter."""

import asyncio
from enum import StrEnum
from pathlib import Path
from typing import Annotated

import typer

from codecongruence import __version__
from codecongruence.core.ai_context import write_ai_context_files
from codecongruence.core.baseline import apply_baseline, baseline_path, load_baseline, save_baseline
from codecongruence.core.config import default_config_path, load_config
from codecongruence.core.embedder import Embedder
from codecongruence.core.git import current_repo_root
from codecongruence.core.runner import RuleRunner
from codecongruence.reporters import JsonReporter, TextReporter

__all__ = ["DEFAULT_TOML", "app"]


class OutputFormat(StrEnum):
    """Output format for violation reporting."""

    text = "text"
    json = "json"


app = typer.Typer(
    name="codecongruence",
    no_args_is_help=False,
    add_completion=False,
    help="Semantic pre-commit checks. Keep your repo congruent — one story, not many.",
)


DEFAULT_TOML = """\
# Generated by `codecongruence init`. Tune thresholds to fit your repo.

[codecongruence]
model = "BAAI/bge-small-en-v1.5"
parallel = true
cache_ttl_days = 30

[rules.docstring_vs_body]
enabled = true
threshold = 0.30

[rules.name_vs_body]
enabled = true
threshold = 0.25

[rules.param_name_vs_usage]
enabled = true
threshold = 0.20

[rules.duplicate_functions]
enabled = true
threshold = 0.92

[rules.params_in_docstring]
enabled = true

[rules.claude_md_vs_diff]
enabled = true
threshold = 0.20

[rules.pr_description_vs_diff]
enabled = false
threshold = 0.25

[rules.stale_comments]
enabled = true
threshold = 0.20

[rules.docs_on_change]
enabled = true
threshold = 0.20
trigger_paths = ["src/**"]
docs_files = ["CHANGELOG.md", "README.md"]
"""


def _ensure_gitignore_entry(repo_root: Path, entry: str = ".codecongruence") -> bool:
    """Add ``entry`` to ``.gitignore`` if absent.

    Args:
        repo_root: Root directory containing (or to contain) the ``.gitignore``.
        entry: The line to add (default: ``".codecongruence"``).

    Returns:
        ``True`` if the entry was added, ``False`` if it was already present.
    """
    gitignore = repo_root / ".gitignore"
    if gitignore.exists():
        text = gitignore.read_text(encoding="utf-8")
        if any(line.strip() == entry for line in text.splitlines()):
            return False
        gitignore.write_text(text.rstrip("\n") + f"\n{entry}\n", encoding="utf-8")
    else:
        gitignore.write_text(f"{entry}\n", encoding="utf-8")
    return True


def _version_callback(value: bool) -> None:
    if value:
        typer.echo(f"codecongruence {__version__}")
        raise typer.Exit


def _purge_models_callback(value: bool) -> None:
    if value:
        import shutil  # noqa: PLC0415

        cache = Path.home() / ".cache" / "codecongruence"
        if cache.exists():
            shutil.rmtree(cache)
            typer.echo(f"removed {cache}")
        else:
            typer.echo(f"nothing to remove ({cache} does not exist)")
        raise typer.Exit


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    rule: Annotated[
        str | None,
        typer.Option("--rule", "-r", help="Run a single rule by id."),
    ] = None,
    config_path: Annotated[
        Path | None,
        typer.Option(
            "--config",
            "-c",
            help=(
                "Path to a TOML config — either a stand-alone codecongruence.toml "
                r"or a pyproject.toml with a \[tool.codecongruence] section. "
                "Auto-detected. Overrides repo-root discovery."
            ),
            exists=True,
        ),
    ] = None,
    all_files: Annotated[
        bool,
        typer.Option("--all", help="Scan the whole repo, not just staged changes."),
    ] = False,
    output_format: Annotated[
        OutputFormat,
        typer.Option("--format", "-f", help="Output format."),
    ] = OutputFormat.text,
    verbose: Annotated[
        bool,
        typer.Option(
            "--verbose", "-v", help="Print the full violation table and an OK line on success."
        ),
    ] = False,
    include_unstaged: Annotated[
        bool,
        typer.Option("--include-unstaged", help="Also check unstaged changes."),
    ] = False,
    update_baseline: Annotated[
        bool,
        typer.Option(
            "--update-baseline",
            help=(
                "Save all current violations as the new baseline and exit 0. "
                "Commit .codecongruence-baseline.json to share with the team."
            ),
        ),
    ] = False,
    debug: Annotated[
        bool,
        typer.Option(
            "--debug",
            help="Emit per-check similarity scores and pass/fail to stderr.",
        ),
    ] = False,
    _purge_models: Annotated[
        bool,
        typer.Option(
            "--purge-models",
            callback=_purge_models_callback,
            is_eager=True,
            help="Delete the model cache (~/.cache/codecongruence) and exit.",
        ),
    ] = False,
    _version: Annotated[
        bool,
        typer.Option(
            "--version",
            callback=_version_callback,
            is_eager=True,
            help="Print version and exit.",
        ),
    ] = False,
) -> None:
    """Run codecongruence on staged changes (default) or the whole repo (``--all``).

    Raises:
        Exit: With code ``1`` when any error-severity violation is found.
    """
    if ctx.invoked_subcommand is not None:
        return

    exit_code = asyncio.run(
        _run(
            rule=rule,
            config_path=config_path,
            all_files=all_files,
            output_format=output_format,
            verbose=verbose,
            include_unstaged=include_unstaged,
            update_baseline=update_baseline,
            debug=debug,
        )
    )
    raise typer.Exit(exit_code)


@app.command(name="init")
def init_cmd(
    path: Annotated[
        Path | None,
        typer.Option("--path", help="Where to write the config (default: repo root)."),
    ] = None,
    force: Annotated[
        bool,
        typer.Option("--force", help="Overwrite an existing config."),
    ] = False,
    no_download: Annotated[
        bool,
        typer.Option("--no-download", help="Skip model download (also skips pre-embedding)."),
    ] = False,
    no_embed: Annotated[
        bool,
        typer.Option("--no-embed", help="Download the model but skip pre-embedding all files."),
    ] = False,
) -> None:
    """Write a default ``codecongruence.toml`` and warm up the embedding model.

    Also writes AI-tool context files so Claude Code, Cursor, and OpenAI
    Codex know how to interpret and fix codecongruence violations:

    - ``.claude/skills/codecongruence.md``
    - ``.cursor/rules/codecongruence.mdc``
    - ``AGENTS.md`` (section appended or file created)

    By default this also downloads the embedding model and pre-embeds every
    tracked file so the first ``git commit`` check is instant. Use
    ``--no-download`` to skip both, or ``--no-embed`` to download the model
    without pre-embedding.

    Args:
        path: Output path for the config file (default: repo root).
        force: If True, overwrite an existing config and AI context files.
        no_download: Skip model download and pre-embedding entirely.
        no_embed: Download model but skip pre-embedding tracked files.

    Raises:
        Exit: With code ``1`` when a config already exists and ``--force`` was not passed.
    """
    repo_root = asyncio.run(current_repo_root())
    target = path or default_config_path(repo_root)
    if target.exists() and not force:
        typer.echo(f"refusing to overwrite {target} (pass --force)")
        raise typer.Exit(code=1)
    target.write_text(DEFAULT_TOML, encoding="utf-8")
    typer.echo(f"wrote {target}")
    if _ensure_gitignore_entry(target.parent):
        typer.echo("added .codecongruence to .gitignore")

    for ai_path, written in write_ai_context_files(repo_root, force=force):
        rel = ai_path.relative_to(repo_root) if ai_path.is_relative_to(repo_root) else ai_path
        if written:
            typer.echo(f"wrote {rel}")
        else:
            typer.echo(f"skipped {rel} (already exists; use --force to overwrite)")

    if no_download:
        return

    asyncio.run(_init_setup(no_embed=no_embed))


async def _init_setup(*, no_embed: bool) -> None:
    from rich.console import Console  # noqa: PLC0415
    from rich.progress import (  # noqa: PLC0415
        BarColumn,
        MofNCompleteColumn,
        Progress,
        SpinnerColumn,
        TextColumn,
    )

    console = Console()

    repo_root = await current_repo_root()
    config = load_config(repo_root=repo_root)
    cache_dir = repo_root / ".codecongruence"
    model_cache_dir = Path.home() / ".cache" / "codecongruence"
    embedder = Embedder(
        model_name=config.model,
        cache_dir=cache_dir,
        model_cache_dir=model_cache_dir,
        threads=config.threads,
        cache_ttl_days=config.cache_ttl_days,
    )

    # Model download may emit fastembed / huggingface_hub tqdm output to stderr.
    # Print a plain line before so it doesn't interleave with any live display.
    console.print(f"[dim]downloading model {config.model!r}…[/dim]")
    await embedder.warm_up()
    console.print("[green]✓[/green] model ready")

    if no_embed:
        return

    runner = RuleRunner(config, embedder)
    changed = await runner.gather_changed(all_files=True)
    before = len(embedder._cache)

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        MofNCompleteColumn(),
        console=console,
        transient=False,
    ) as progress:
        task = progress.add_task(f"embedding {len(changed)} file(s)", total=len(changed))
        for cf in changed:
            await runner.run(pre_gathered=[cf])
            progress.advance(task)

    embedder.save(force_cleanup=True)
    added = len(embedder._cache) - before
    console.print(f"[green]✓[/green] cached {len(embedder._cache)} embedding(s) ({added} new)")


async def _run(
    *,
    rule: str | None,
    config_path: Path | None,
    all_files: bool,
    output_format: OutputFormat,
    verbose: bool,
    include_unstaged: bool,
    update_baseline: bool = False,
    debug: bool = False,
) -> int:
    if debug:
        import logging  # noqa: PLC0415

        handler = logging.StreamHandler()
        handler.setFormatter(logging.Formatter("%(name)s  %(message)s"))
        logger = logging.getLogger("codecongruence")
        logger.setLevel(logging.DEBUG)
        logger.addHandler(handler)

    repo_root = await current_repo_root()
    config = load_config(path=config_path, repo_root=repo_root)
    cache_dir = repo_root / ".codecongruence"
    model_cache_dir = Path.home() / ".cache" / "codecongruence"
    embedder = Embedder(
        model_name=config.model,
        cache_dir=cache_dir,
        model_cache_dir=model_cache_dir,
        threads=config.threads,
        cache_ttl_days=config.cache_ttl_days,
    )
    runner = RuleRunner(config, embedder)
    changed = await runner.gather_changed(all_files=all_files, include_unstaged=include_unstaged)

    if verbose and output_format is OutputFormat.text:
        from rich.console import Console  # noqa: PLC0415

        selected_preview = runner._select_rules(rule)
        Console().print(
            f"[dim]codecongruence: scanning {len(changed)} file(s) "
            f"with {len(selected_preview)} rule(s)…[/dim]"
        )

    result = await runner.run(
        only=rule,
        pre_gathered=changed,
    )

    embedder.save(force_cleanup=all_files)

    if update_baseline:
        bl_path = baseline_path(repo_root)
        save_baseline(result.violations, bl_path)
        typer.echo(
            f"codecongruence: saved {len(result.violations)} violation(s) to "
            f"{bl_path.relative_to(repo_root)}"
        )
        if result.violations:
            typer.echo(
                "Commit .codecongruence-baseline.json to share across the team. "
                "Future runs will only fail on new violations."
            )
        return 0

    bl = load_baseline(baseline_path(repo_root))
    suppressed = 0
    if bl is not None:
        result, suppressed = apply_baseline(result, bl)

    if output_format is OutputFormat.json:
        JsonReporter().report(result)
    else:
        TextReporter(verbose=verbose).report(result)
        if suppressed > 0:
            from rich.console import Console  # noqa: PLC0415

            Console().print(
                f"[dim]{suppressed} violation(s) suppressed by baseline "
                "(run --update-baseline to reset)[/dim]"
            )

    return 0 if result.ok else 1


if __name__ == "__main__":  # pragma: no cover
    app(prog_name="codecongruence")
