"""Typer CLI entry. Wires config → embedder → runner → reporter."""

import asyncio
from enum import StrEnum
from pathlib import Path
from typing import Annotated

import typer

from codecongruence import __version__
from codecongruence.core.config import default_config_path, load_config
from codecongruence.core.embedder import Embedder
from codecongruence.core.git import current_repo_root
from codecongruence.core.runner import RuleRunner
from codecongruence.reporters import JsonReporter, TextReporter

__all__ = ["app"]


class OutputFormat(StrEnum):
    """Output format for violation reporting."""

    text = "text"
    json = "json"


app = typer.Typer(
    name="codecongruence",
    no_args_is_help=False,
    add_completion=False,
    help="Semantic pre-commit checks. Keep your repo congruent — one story, not many.",
)


_DEFAULT_TOML = """\
# Generated by `codecongruence init`. Tune thresholds to fit your repo.

[codecongruence]
model = "BAAI/bge-small-en-v1.5"
parallel = true

[rules.docstring_vs_body]
enabled = true
threshold = 0.30

[rules.name_vs_body]
enabled = true
threshold = 0.25

[rules.claude_md_vs_diff]
enabled = true
threshold = 0.20

[rules.pr_description_vs_diff]
enabled = false
threshold = 0.25

[rules.stale_comments]
enabled = true
threshold = 0.20

[rules.changelog_exists]
enabled = true
"""


def _ensure_gitignore_entry(repo_root: Path, entry: str = ".codecongruence") -> bool:
    """Add ``entry`` to ``.gitignore`` if absent.

    Returns:
        ``True`` if the entry was added, ``False`` if it was already present.
    """
    gitignore = repo_root / ".gitignore"
    if gitignore.exists():
        text = gitignore.read_text(encoding="utf-8")
        if any(line.strip() == entry for line in text.splitlines()):
            return False
        gitignore.write_text(text.rstrip("\n") + f"\n{entry}\n", encoding="utf-8")
    else:
        gitignore.write_text(f"{entry}\n", encoding="utf-8")
    return True


def _version_callback(value: bool) -> None:
    if value:
        typer.echo(f"codecongruence {__version__}")
        raise typer.Exit


@app.callback(invoke_without_command=True)
def main(
    ctx: typer.Context,
    rule: Annotated[
        str | None,
        typer.Option("--rule", "-r", help="Run a single rule by id."),
    ] = None,
    config_path: Annotated[
        Path | None,
        typer.Option(
            "--config",
            "-c",
            help=(
                "Path to a TOML config — either a stand-alone codecongruence.toml "
                r"or a pyproject.toml with a \[tool.codecongruence] section. "
                "Auto-detected. Overrides repo-root discovery."
            ),
            exists=True,
        ),
    ] = None,
    all_files: Annotated[
        bool,
        typer.Option("--all", help="Scan the whole repo, not just staged changes."),
    ] = False,
    output_format: Annotated[
        OutputFormat,
        typer.Option("--format", "-f", help="Output format."),
    ] = OutputFormat.text,
    verbose: Annotated[
        bool,
        typer.Option(
            "--verbose", "-v", help="Print the full violation table and an OK line on success."
        ),
    ] = False,
    include_unstaged: Annotated[
        bool,
        typer.Option("--include-unstaged", help="Also check unstaged changes."),
    ] = False,
    _version: Annotated[
        bool,
        typer.Option(
            "--version",
            callback=_version_callback,
            is_eager=True,
            help="Print version and exit.",
        ),
    ] = False,
) -> None:
    """Run codecongruence on staged changes (default) or the whole repo (``--all``).

    Raises:
        Exit: With code ``1`` when any error-severity violation is found.
    """
    if ctx.invoked_subcommand is not None:
        return

    exit_code = asyncio.run(
        _run(
            rule=rule,
            config_path=config_path,
            all_files=all_files,
            output_format=output_format,
            verbose=verbose,
            include_unstaged=include_unstaged,
        )
    )
    raise typer.Exit(exit_code)


@app.command(name="init")
def init_cmd(
    path: Annotated[
        Path | None,
        typer.Option("--path", help="Where to write the config (default: repo root)."),
    ] = None,
    force: Annotated[
        bool,
        typer.Option("--force", help="Overwrite an existing config."),
    ] = False,
) -> None:
    """Write a default ``codecongruence.toml`` at the repo root.

    Raises:
        Exit: With code ``1`` when a config already exists and ``--force`` was not passed.
    """
    target = path or default_config_path()
    if target.exists() and not force:
        typer.echo(f"refusing to overwrite {target} (pass --force)")
        raise typer.Exit(code=1)
    target.write_text(_DEFAULT_TOML, encoding="utf-8")
    typer.echo(f"wrote {target}")
    if _ensure_gitignore_entry(target.parent):
        typer.echo("added .codecongruence to .gitignore")


async def _run(
    *,
    rule: str | None,
    config_path: Path | None,
    all_files: bool,
    output_format: OutputFormat,
    verbose: bool,
    include_unstaged: bool,
) -> int:
    repo_root = await current_repo_root()
    config = load_config(path=config_path, repo_root=repo_root)
    cache_dir = repo_root / ".codecongruence"
    embedder = Embedder(model_name=config.model, cache_dir=cache_dir)
    runner = RuleRunner(config, embedder)

    result = await runner.run(
        only=rule,
        all_files=all_files,
        include_unstaged=include_unstaged,
    )

    if output_format is OutputFormat.json:
        JsonReporter().report(result)
    else:
        TextReporter(verbose=verbose).report(result)

    return 0 if result.ok else 1


if __name__ == "__main__":  # pragma: no cover
    app(prog_name="codecongruence")
